
// For testing
// Using REST client extension in VS code
// You can use postman instead
POST http://localhost:3000/api/doctors/add_doctor
content-type: application/json

{
      "ssn": "12345678901234",
      "title": "something",
      "first_name": "something",
      "last_name":"something",
      "email": "something",
      "gender": "something",
      "salary": 12345,
      "phone_number": 12345,
      "password": "something"
}

